
name: Spring Core - Tests

on:
  push:
    branches: [ "develop, master" ]

jobs:
  build:
    name: Test - Unit & Integration & SonarCloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Unit & Integration Tests
      run: mvn -B verify
      env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }
    - name: Sonar
      if: success()
      run: >
        mvn -B verify -DskipTests sonar:sonar
        -Dsonar.projectKey=danielhdzf_core
        -Dsonar.organization=danielhdzf
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
