
name: Spring Core - Tests

on:
  push:
    branches: [ "develop", "master" ]

jobs:
  build:
    name: Test - Unit & Integration & SonarCloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 0 }
    - uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Set up MongoDB
      run: |
        docker run --name mongo-instance -d -p 27017:27017 mongo:latest
        sleep 15
    - name: Unit & Integration Tests
      run: mvn -B verify
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SPRING_DATA_MONGODB_HOST: localhost
        SPRING_DATA_MONGODB_PORT: 27017
    - name: Sonar
      if: success()
      run: >
        mvn -B verify -DskipTests sonar:sonar
        -Dsonar.projectKey=danielhdzf_core
        -Dsonar.organization=danielhdzf
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
